name       : python3-qtwebengine
version    : 5.12.1
release    : 2
source     :
    - https://www.riverbankcomputing.com/static/Downloads/PyQtWebEngine/5.12.1/PyQtWebEngine_gpl-5.12.1.tar.gz : 860704672ea1b616e1347be1f347bc1c749e64ed378370863fe209e84e9bd473
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python 3 bindings for QtWebEngine
description: |
    A set of Python3 bindings for the Qt Company's Qt WebEngine libraries.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5WebEngine)
    - python3-qt5
    - python3-sip-devel
setup      : |
    python3 configure.py --no-sip-files
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir" -j1
